version: '3.8'

services:
  # CPU-only version
  tts-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: tts-converter-cpu
    ports:
      - "8007:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # CUDA-enabled version (requires nvidia-docker)
  tts-cuda:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    container_name: tts-converter-cuda
    ports:
      - "8001:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  storage:
    driver: local
